# <font color='#154360'> <b> <center> Embedding Layer </center> </b> </font>

The embedding layer turns positive integers (indexes) into dense vectors of fixed size.

e.g. [[4], [20]] -> [[0.25, 0.1], [0.6, -0.2]]

<br>

<b>tf_keras.layers.Embedding</b>(
    
    input_dim,
    
    output_dim,
    
    embeddings_initializer="uniform",
    
    embeddings_regularizer=None,
    
    activity_regularizer=None,
    
    embeddings_constraint=None,
    
    mask_zero=False,
    
    input_length=None,
    
    sparse=False,
    
    **kwargs
)

In [4]:
import keras
import numpy as np

In [11]:
from tensorflow import keras
import numpy as np

# Smaller vocabulary size and embedding dimension for clarity
vocab_size = 20       # Just 20 words in the vocab
embed_dim = 4         # 4-dimensional embeddings
input_length = 5      # Input sentences are 5 words long

# Create a simple model
model = keras.Sequential([
    keras.layers.Embedding(input_dim=vocab_size,
                           output_dim=embed_dim,
                           input_length=input_length)
])

# Print model summary
model.summary()

# Sample input: batch of 2 "sentences", each with 5 word indices
sample_input = np.array([[1, 5, 2, 3, 0],
                         [4, 3, 1, 2, 7]])

# Run the model and print the output shape and values
output = model(sample_input)

print("Input shape:", sample_input.shape)         # (2, 5)
print("Output shape:", output.shape)              # (2, 5, 4)
print("Output[0]:\n", output[0].numpy())          # Embeddings for first sentence



print("\n--------------------------------------------------\n")

# Print first input sentence and its embedding
print("First input sentence (word indices):", sample_input[0])
print("\nEmbedding vectors (shape {}):\n".format(output[0].shape))

# Loop through each word in the sentence
for i, (word_index, embedding_vector) in enumerate(zip(sample_input[0], output[0])):
    print(f"Word {i+1} (index {word_index}): {embedding_vector.numpy()}")



Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_6 (Embedding)     (None, 5, 4)              80        
                                                                 
Total params: 80 (320.00 Byte)
Trainable params: 80 (320.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Input shape: (2, 5)
Output shape: (2, 5, 4)
Output[0]:
 [[ 0.00069342  0.02237742  0.01575348  0.00660519]
 [-0.00233923 -0.01528187 -0.03285794 -0.03849189]
 [-0.02080202 -0.02496007 -0.02483844 -0.0109459 ]
 [-0.03111447  0.04475241 -0.03555129  0.01432693]
 [-0.02373142  0.03111067 -0.04798113 -0.01596048]]

--------------------------------------------------

First input sentence (word indices): [1 5 2 3 0]

Embedding vectors (shape (5, 4)):

Word 1 (index 1): [0.00069342 0.02237742 0.01575348 0.00660519]
Word 2 (index 5): [-0.00233923 -

In [12]:
output[0].shape

TensorShape([5, 4])

### References

[Embedding Layer](https://keras.io/2.15/api/layers/core_layers/embedding/)